//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PCDraft.rc
//
#define IDB_APPLY                       3
#define IDC_NAME                        4
#define IDC_VALUE1                      10
#define IDC_VALUE2                      11
#define IDC_VALUE3                      12
#define IDC_VALUE4                      13
#define IDC_VALUE5                      14
#define IDC_VALUE6                      15
#define IDD_ABOUTBOX                    100
#define IDC_NEW                         100
#define IDC_PRINTER                     100
#define IDC_COPY_ONLY                   100
#define IDC_EXISTING_LINE               101
#define IDC_PL_ALIGN1                   101
#define IDC_SMALLER_ARC                 101
#define IDC_LENGTH1                     101
#define IDC_MIRROR                      101
#define IDC_SIDES                       101
#define IDC_VIEW_NAME                   101
#define IDC_WHITE                       101
#define IDC_LOAD                        101
#define IDC_SCREEN                      101
#define IDC_LINK_RESULTS                101
#define IDC_CLONE_AGAIN                 101
#define IDC_FRACTIONAL                  101
#define IDC_RENAME_TEXT                 101
#define IDC_RENAME_PROMPT               101
#define IDC_REFERENCE_LINE              102
#define IDC_PL_ALIGN2                   102
#define IDC_LARGER_ARC                  102
#define IDC_LENGTH2                     102
#define IDC_MIRROR_COPY                 102
#define IDC_WIT_EXTENSION               102
#define IDC_USE_KEY                     102
#define IDC_BLACK                       102
#define IDC_LINK_ALL                    102
#define IDC_BREAK_CLONE                 102
#define IDC_DECIMAL_INCH                102
#define IDC_DECIMAL                     102
#define IDC_THICKNESS                   102
#define IDC_PL_ALIGN3                   103
#define IDC_AUTO_TRIM                   103
#define IDC_TEXT_CENTERED               103
#define IDC_WIT_LINE_GAP                103
#define IDC_RETAIN_CLONE                103
#define IDC_DECIMAL_FEET                103
#define IDD_DIALOGBAR                   103
#define IDC_PL_ENDCAP1                  104
#define IDC_MANUAL_TRIM                 104
#define IDC_TEXT_FRAMED                 104
#define IDC_DIM_TEXT_GAP                104
#define IDC_PL_ENDCAP2                  105
#define IDC_NO_TRIM                     105
#define IDC_WITNESS_LINES               105
#define IDC_LEADER_LENGTH               105
#define IDC_PL_ENDCAP3                  106
#define IDC_RADIUS                      106
#define IDC_ARROWS_INSIDE               106
#define IDC_OUTSIDE_LINE_LENGTH         106
#define IDC_PL_ENDCAP4                  107
#define IDC_DIM_ROUNDOFF                107
#define IDC_TOL_TEXT_SCALE              107
#define IDC_PL_JOINT1                   108
#define IDC_LEADER                      108
#define IDC_TOL_SPACE_SCALE             108
#define IDC_INPLACEEDIT                 108
#define IDC_PL_JOINT2                   109
#define IDC_RDSYMBOL                    109
#define IDC_CIRCLE_CENTER_LENGTH        109
#define IDC_LINE_WIDTH                  110
#define IDC_TOLERANCE                   110
#define IDC_CIRCLE_CENTER_GAP           110
#define IDC_SELINFO                     110
#define IDC_TOL1                        111
#define IDC_CIRCLE_CENTER_EXT           111
#define IDC_LIMITS                      111
#define IDC_PRINT                       111
#define IDC_TOL2                        112
#define IDC_PRINTSETUP                  112
#define IDC_TOL1_MEASURE                113
#define IDC_UPDATE                      113
#define IDC_TOL2_MEASURE                114
#define IDC_DIM_LABEL                   115
#define IDC_LABEL                       116
#define IDC_STANDARDS                   117
#define CG_IDD_PROGRESS                 118
#define IDR_MAINFRAME                   128
#define IDR_PCDRAFTTYPE                 129
#define IDR_STATIONARYTYPE              130
#define IDR_SYMBOL_LIBRARY              131
#define IDR_LIBRARY                     132
#define IDR_LAYER                       133
#define IDR_PCMACDRAFTTYPE              134
#define IDD_SCALE_UNITS                 135
#define IDS_DDE_TITLE                   135
#define IDR_WELCOME                     136
#define IDD_DRAWING_SIZE                138
#define IDS_ENGLISH_SCALE_FIRST         139
#define IDC_HAND_DRAFT                  140
#define IDI_PAGE_NUMBERING_1234         140
#define IDC_BUCKET                      141
#define IDI_PAGE_NUMBERING_1324         144
#define IDB_DASH_INCH                   147
#define IDB_DASH_CM                     148
#define IDC_MID_CROSS                   152
#define IDB_TOOL_TEXT                   154
#define IDB_TOOL_ARROW                  155
#define IDB_TOOL_1_1                    156
#define IDB_TOOL_ROTATE_90              157
#define IDB_TOOL_UNGLUE                 158
#define IDB_TOOL_FILLET                 159
#define IDB_TOOL_CHAMFER                160
#define IDB_TOOL_ARC                    161
#define IDB_TOOL_REGULAR_POLY           162
#define IDS_ENGLISH_SCALE_LAST          163
#define IDB_TOOL_CONSTR_LINE            163
#define IDS_METRIC_SCALE_FIRST          164
#define IDB_TOOL_CURVE                  164
#define IDB_TOOL_ELLIPSE                165
#define IDB_TOOL_PARALLEL_LINE          166
#define IDB_TOOL_PERP_LINE              167
#define IDB_TOOL_POLY                   168
#define IDB_TOOL_RC                     169
#define IDB_TOOL_RECT                   170
#define IDB_TOOL_CIRCLE                 171
#define IDB_COLOR_PICKER                173
#define IDB_PATTERN_PICKER              174
#define IDC_DRAG                        175
#define IDC_SMALL_CROSS                 176
#define IDC_POINTING_HAND               177
#define IDC_OPTION_HAND                 178
#define IDC_ROTATE                      179
#define IDC_HANDLE_SPLIT                180
#define IDC_OBJECT_FILL                 181
#define IDC_OBJECT_PEN                  182
#define IDC_HANDLE_REMOVE               182
#define IDC_ZOOMIN                      183
#define IDC_ZOOMOUT                     184
#define IDS_METRIC_SCALE_LAST           185
#define IDC_SHAPE_DRAG                  186
#define IDS_AUTOMATIC                   186
#define IDC_ERASER                      187
#define IDC_REPEAT_PASTE                188
#define IDS_ENGLISH_UNITS               188
#define IDC_ROTATE_ON_PT                189
#define IDS_ANSI_UNITS                  189
#define IDC_WHICH                       190
#define IDS_METRIC_UNITS                190
#define IDC_OBJECT_INFO                 191
#define IDC_HCONSTRAIN                  191
#define IDS_GENERAL_SHAPE_FIRST         191
#define IDC_VCONSTRAIN                  192
#define IDC_EXTRUDE_PLINE               194
#define IDC_EXTRUDE_PPOLY               195
#define IDC_QUESTION                    198
#define IDC_POINTER                     199
#define IDC_ATTRIB_PICK                 201
#define IDC_ATTRIB_DROP                 202
#define IDD_LAYER_SETUP                 203
#define IDC_ATTRIB_DROP_OPT             203
#define IDC_ATTRIB_DROP_LOCK            204
#define IDD_ALIGNMENT_OPTIONS           205
#define IDC_ATTRIB_PICK_QUERY           205
#define IDS_GENERAL_SHAPE_LAST          205
#define IDC_ATTRIB_DROP_QUERY           206
#define IDD_EDIT_LINE_STYLE             207
#define IDC_FIRST                       207
#define IDC_SPLIT                       210
#define IDC_END_SNAP                    211
#define IDS_DIMENSION_TYPE_FIRST        211
#define IDC_MID_SNAP                    212
#define IDC_CENTER_SNAP                 213
#define IDB_TOOL_ATTRIB_DROP            214
#define IDB_TOOL_MARKER                 215
#define IDB_TOOL_ZOOM                   216
#define IDS_DIMENSION_TYPE_LAST         219
#define IDD_DIM_STANDARD                220
#define IDB_TOOL_GLUE                   220
#define IDD_EDIT_DIM_STANDARD           221
#define IDB_TOOL_COMBINE                221
#define IDD_DIM_FORMAT                  222
#define IDI_ACTIVE_LAYER                222
#define IDB_TOOL_SUBTRACT               222
#define IDD_EDIT_DIM_FORMAT             223
#define IDI_VISIBLE_LAYER               223
#define IDB_TOOL_EXTEND                 223
#define IDB_TOOL_TRIM                   224
#define IDB_TOOL_MIRROR                 225
#define IDB_TOOL_DIM_HORIZ              226
#define IDB_TOOL_DIM_VERT               227
#define IDB_TOOL_DIM_SLOPE              228
#define IDB_TOOL_DIM_PERP               229
#define IDS_TOOL_DIM_FORMAT             229
#define IDB_TOOL_DIM_RADIUS             231
#define IDS_FUNCTION_NAME               231
#define IDB_TOOL_DIM_CENTER             232
#define IDB_TOOL_DIM_ANGULAR            233
#define IDB_TOOL_HANDLE                 234
#define IDD_PRINT_SLIDES                240
#define IDB_ABOUT                       240
#define IDB_ABOUT2                      241
#define IDD_ATTRIB_PALETTE              242
#define IDS_FUNCTION_TOTAL_NAME         242
#define IDS_FUNCTION_TOTAL_FORMAT       243
#define IDS_CRITERIA_UNDEFINED          244
#define IDS_CRITERIA_NAME               245
#define IDS_CRITERIA_RESULTS            246
#define IDB_PEN                         247
#define IDS_CRITERIA_FXNAME             247
#define IDB_BUCKET                      248
#define IDS_OVERWRITEPROMPT             248
#define IDS_DELETE_ALL_VIEWS            249
#define IDD_CIRCLE_DUP                  251
#define IDB_ENDMARK_PICKER              251
#define IDB_WIDTH_PICKER                252
#define IDB_STYLE_PICKER                253
#define IDB_PL_JOINT2                   254
#define IDB_PL_JOINT1                   255
#define IDB_PL_ENDCAP1                  256
#define IDB_PL_ALIGN1                   257
#define IDB_PE_THUMB                    262
#define IDB_PE_HAND                     263
#define IDB_PE_BUCKET                   264
#define IDB_PE_PEN                      265
#define IDB_PE_FLIPV                    266
#define IDB_PE_FLIPH                    267
#define IDB_PE_INVERT                   268
#define IDD_CHOOSE_COLOR                270
#define IDB_THUMB_MASK                  271
#define IDB_LAYER_BAR                   272
#define IDD_SYMBOL_LIBRARY_FORM         273
#define IDB_ALIGN_GRID                  274
#define IDR_REPORT_POPUP                277
#define IDR_MENU1                       278
#define IDB_PATDOT                      279
#define IDR_REPORTYPE                   279
#define IDR_REPORTTYPE                  279
#define IDB_REPORT                      280
#define IDD_SHOWSIZE_PALETTE            281
#define IDB_CURSOR_PROMPTS              282
#define IDD_SELECT_VIEW                 284
#define IDB_TOOL_MARK                   286
#define IDB_TOOL_MASK                   287
#define IDD_REPORT_CLONE                288
#define IDB_ANNOT_A                     294
#define IDB_ANNOT_B                     295
#define IDB_RESIZE_MORE                 296
#define IDB_RESIZE_LESS                 297
#define IDR_PCDRAFT_POPUP               299
#define IDS_METRIC_GRIDS                301
#define IDD_SYMBOL_TOOL_FORM            305
#define IDB_REGISTRATION                306
#define IDB_DEMO_CLIPBOARD              308
#define IDR_ADINIT_DAT                  309
#define IDB_MINI_MAXIMIZE               311
#define IDB_MINI_RESTORE                312
#define IDD_EXPAND                      313
#define IDD_CONTRACT_EXPAND             313
#define IDB_ALIGN_LEFT                  314
#define IDB_PFILL                       315
#define IDI_LINKED                      316
#define IDB_LINE                        319
#define IDD_DWG_UNITS                   320
#define IDD_BREAK_PARALLEL_SHAPE        321
#define IDI_PENSTYLE_BLADE              322
#define IDI_PENSTYLE_ROUND              323
#define IDD_MULTIPLE_UNLINK             325
#define IDD_BADDWGOBJECT                326
#define IDD_CHANGE_USER                 328
#define IDB_TRANSPARENCY                330
#define IDR_XML1                        341
#define IDD_LIBRARY                     342
#define IDD_LIBRARY_FOOTER              342
#define IDB_LIBRARY32                   345
#define IDD_SELECT_SPECIAL              350
#define IDS_ENGLISH_DEC_GRIDS           351
#define IDI_SEARCH                      354
#define IDB_SHORTCUT                    355
#define IDD_SELECT_OBJECT_INFO          360
#define IDD_MOVE_OBJECT                 365
#define IDD_ATTRIBUTE_OPTIONS           366
#define IDB_PNG_LAYER_ACTIVE            366
#define IDB_PNG_LAYER_GRAYED            367
#define IDB_PNG_LAYER_VISIBLE           368
#define IDB_PNG_LAYER_HIDDEN            369
#define IDD_FIELD_NAMES                 370
#define IDD_OBJECT_INFO                 371
#define IDB_PNG_LAYER_LOCKED            371
#define IDB_PNG_LAYER_DROPDOWN          372
#define IDR_PCDRAFTTYPE2                374
#define IDD_FIND_REPLACE                375
#define IDI_CAPTION_SAVE                375
#define IDI_CAPTION_UNDO                376
#define IDI_CAPTION_REDO                377
#define IDI_RIBBON_HELP                 378
#define IDI_RIBBON_COLLAPSE             379
#define IDI_RIBBON_EXPAND               380
#define IDB_BITMAP1                     381
#define IDB_LEFT_ARROW                  381
#define IDR_LIBRARY1                    381
#define IDR_MAINFRAME1                  381
#define IDB_BITMAP2                     383
#define IDB_RESIZE_GRIP                 383
#define IDR_MENU2                       384
#define IDR_MRU                         384
#define IDC_SPLITH                      389
#define IDR_CONTEXT_OBJECTS             390
#define IDR_CONTEXT_TEXT                391
#define IDR_CONTEXT_IMAGE               392
#define IDR_CONTEXT_NO_SELECTION        393
#define IDB_PNG1                        394
#define IDB_PNG_WELCOME_ICON            394
#define IDB_PNG_WELCOME_CHECKED         395
#define IDR_ACCELERATOR1                396
#define IDB_PNG2                        397
#define IDB_PNG_WELCOME_UNCHECKED       397
#define IDB_PNG_MAINFRAME_256           398
#define IDB_PNG4                        399
#define IDB_PNG_WELCOME_FOLDER          400
#define IDS_ENGLISH_FRAC_GRIDS          401
#define IDB_PNG_WELCOME_HELP            401
#define IDB_PNG_WELCOME_NEW             402
#define IDB_PNG5                        403
#define IDB_PNG_WELCOME_TEMPLATE        403
#define IDB_PNG_PC                      404
#define IDB_PNG_PCDRAFT_DOC48           404
#define IDB_PNG3                        405
#define IDB_PNG_COMPASS_BORDERED        405
#define IDD_RENAME                      450
#define IDS_ENGLISH_DEC_FT_GRIDS        451
#define IDS_STANDARD                    490
#define IDS_CUSTOM                      491
#define IDS_PLACESFIRST                 492
#define IDS_PLACESLAST                  496
#define IDS_TYPEFIRST                   497
#define IDD_VIEW_NAME                   500
#define IDD_SAVE_VIEW                   500
#define IDS_TYPELAST                    500
#define IDD_NEWDOC_DEFAULTS             501
#define IDS_UNDO                        501
#define IDD_APPLICATION_DEFAULTS        502
#define IDS_REDO                        502
#define IDS_CANTUNDO                    503
#define IDS_RESELECT                    504
#define IDD_POSITION                    505
#define IDS_CREATION                    505
#define IDS_DELETE                      506
#define IDS_DUPLICATE                   507
#define IDS_BRINGTOFRONT                508
#define IDS_SENDTOBACK                  509
#define IDS_MOVEFORWARD                 510
#define IDS_MOVEBACK                    511
#define IDS_CUT                         512
#define IDS_COPY                        513
#define IDS_PASTE                       514
#define IDS_FILLCHANGE                  515
#define IDS_PENCHANGE                   516
#define IDS_MOVE                        517
#define IDS_RESIZE                      518
#define IDS_GROUP                       519
#define IDS_UNGROUP                     520
#define IDS_ROTATE                      521
#define IDS_ADDVERTEX                   522
#define IDS_SUBVERTEX                   523
#define IDS_PARAFILLCHANGE              524
#define IDS_FLIP                        525
#define IDS_ROTATETOZERO                526
#define IDS_PARAATTRCHANGE              527
#define IDS_ENDMARK                     528
#define IDS_TEXTFONT                    529
#define IDS_TEXTSIZE                    530
#define IDS_TEXTSTYLE                   531
#define IDS_SPACING                     532
#define IDS_TEXTSPACE                   532
#define IDS_TEXTJUST                    533
#define IDS_TEXTCASE                    534
#define IDS_SMOOTH                      535
#define IDS_UNSMOOTH                    536
#define IDS_TEXTKEY                     537
#define IDS_TEXTCUT                     538
#define IDS_TEXTCLEAR                   539
#define IDS_TEXTPASTE                   540
#define IDS_ALIGN                       541
#define IDS_DISTRIBUTEONLINE            542
#define IDS_LOCK                        543
#define IDS_UNLOCK                      544
#define IDS_LINESTYLECHANGE             545
#define IDS_DIMTEXT                     546
#define IDS_POSITION                    547
#define IDS_CROP                        548
#define IDS_DIMFORMAT                   549
#define IDS_BREAK                       550
#define IDS_EXTEND                      551
#define IDS_TRIM                        552
#define IDS_FILLET                      553
#define IDS_CHAMFER                     554
#define IDS_EXTRUDE                     555
#define IDS_DUPLICATION                 556
#define IDS_ATTACH                      557
#define IDS_COMBINE                     558
#define IDS_SUBTRACT                    559
#define IDS_MIRROR                      560
#define IDS_REPLACE                     561
#define IDS_ATTACHPOLY                  562
#define IDS_DROPDATA                    563
#define IDS_EYE_DROPPER                 564
#define IDS_PENSTYLE                    565
#define IDS_CONTRACT                    566
#define IDS_EXPAND                      567
#define IDS_CUSTOM_SCALE                568
#define IDD_REPORT_FORMATS              600
#define IDD_REPORT_OUTPUT               601
#define IDS_DIMENSION                   601
#define IDD_CLONE_OPTIONS               602
#define IDS_LINE                        602
#define IDS_LENGTH                      603
#define IDS_ANGLE                       604
#define IDD_CLONE_UNITS                 604
#define IDS_RECTANGLE                   605
#define IDD_CLONE_FT_IN_UNIT            605
#define IDS_ELLIPSE                     606
#define IDD_CLONE_AGAIN                 606
#define IDS_RGROUP                      607
#define IDS_RNDRECT                     608
#define IDS_WIDTH                       609
#define IDS_HEIGHT                      610
#define IDS_R                           611
#define IDS_ELLIP_RECT                  612
#define IDS_XR                          615
#define IDS_YR                          616
#define IDS_CIRCLE                      617
#define IDS_RADIUS                      618
#define IDS_DIA                         620
#define IDS_CIRCLE3P                    621
#define IDS_ARC3P                       622
#define IDS_1X                          623
#define IDS_Y                           624
#define IDS_2X                          625
#define IDS_3X                          627
#define IDS_ANGDIM                      629
#define IDS_ARC                         630
#define IDS_1A                          631
#define IDS_ENDA                        632
#define IDS_EARC                        634
#define IDS_EDIT_COORD                  639
#define IDS_X                           640
#define IDS_METAPOLY                    642
#define IDS_PERCENT                     643
#define IDS_CANT_OPEN_WEB_PAGE          644
#define IDS_MORE_THAN_ONE               645
#define IDS_INVALID_FIND_SHAPE          645
#define IDS_INVALID_REPLACE_SHAPE       646
#define IDS_QUERY_DELETE_LAYER          647
#define IDS_INVALID_SHAPE               648
#define IDS_BETA_SECONDS                649
#define IDS_LAYER_SETUP                 650
#define IDS_LAYER_SETUP_NODOC           651
#define IDS_CANT_MERGE_LAYERS           652
#define IDS_DEGREE_SYMBOL               653
#define IDS_MINUTE_SYMBOL               654
#define IDS_SECOND_SYMBOL               655
#define IDS_DEGREE_ABBR                 656
#define IDS_MINUTE_SYMBOL2              657
#define IDS_MINUTE_ABBR                 658
#define IDS_SECOND_SYMBOL2              659
#define IDS_SECOND_ABBR                 660
#define IDS_FOOT_SYMBOL                 661
#define IDS_FOOT_SYMBOL2                662
#define IDS_FOOT_ABBR                   663
#define IDS_INCH_SYMBOL                 664
#define IDS_INCH_SYMBOL2                665
#define IDS_INCH_ABBR                   666
#define IDS_MILLIMETER_ABBR             667
#define IDS_CENTIMETER_ABBR             668
#define IDS_DECIMETER_ABBR              669
#define IDS_METER_ABBR                  670
#define IDS_MANUAL_NOT_FOUND            671
#define IDS_ACROBAT_NOT_FOUND           672
#define IDS_MANUAL                      673
#define IDS_FIELD1                      674
#define IDS_FIELD2                      675
#define IDS_FIELD3                      676
#define IDS_FIELD4                      677
#define IDS_FIELD5                      678
#define IDS_INCHES_ABBR2                679
#define IDS_EMPTYPROMPT                 680
#define IDS_CLICKPOINT                  681
#define IDS_1POINT                      682
#define IDS_2POINT                      683
#define IDS_NEXTPOINT                   684
#define IDS_CLICKREFERENCEPOINT         685
#define IDS_CLICKOBJECT                 686
#define IDS_CLICKREFERENCEOBJECT        687
#define IDS_ANCHOR                      688
#define IDS_CLICKARC                    689
#define IDS_CLICKCIRCLE                 690
#define IDS_CLICKLINEARC                691
#define IDS_CLICKLINEEDGE               692
#define IDS_1LINEEDGE                   693
#define IDS_2LINEEDGE                   694
#define IDS_CLICKCIRCLEARC              695
#define IDS_CLICK1CIRCLEARC             696
#define IDS_1CIRCLEARC                  697
#define IDS_2CIRCLEARC                  698
#define IDS_LEADINGDIAMETER             710
#define IDS_TRAILINGDIAMETER            711
#define IDS_LEADINGRADIUS               712
#define IDS_TRAILINGRADIUS              713
#define IDS_UNITFIRST                   720
#define IDS_UNITLAST                    727
#define IDS_FRACBAR                     730
#define IDS_DASH                        731
#define IDS_ENDASH                      732
#define IDS_EMDASH                      733
#define IDS_ZOOMDIVIDE                  735
#define IDS_ZOOMMULTIPLY                736
#define IDS_ZOOMSYMBOL                  737
#define IDS_DIMTYPEFIRST                740
#define IDS_DIMTYPELAST                 742
#define IDS_DISPLAYFIRST                750
#define IDS_DISPLAYLAST                 753
#define IDS_LEADERFIRST                 760
#define IDS_LEADERLAST                  762
#define IDS_RDSYMBOLFIRST               770
#define IDS_RDSYMBOLLAST                772
#define IDS_TOLERANCEFIRST              780
#define IDS_TOLERANCELAST               783
#define IDS_ABSOLUTEX                   785
#define IDS_ABSOLUTEY                   786
#define IDS_RELATIVEX                   787
#define IDS_RELATIVEY                   788
#define IDS_ROUNDOFF                    790
#define IDS_REPLACEFIRST                791
#define IDS_REPLACELAST                 793
#define IDS_DUPDISTANCE                 795
#define IDS_DUPANGLE                    796
#define IDS_DUPDELTAX                   797
#define IDS_DUPDELTAY                   798
#define IDS_INCHES                      800
#define IDS_MILLIMETERS                 801
#define IDS_CLONE                       805
#define IDS_HOMEURL                     810
#define IDS_REGISTERURL                 811
#define IDS_UPGRADEURL                  812
#define IDS_SHOWSIZE_BASE               820
#define IDD_EDIT_PATTERN                999
#define IDS_CANT_DELETE_LAYER           1000
#define IDC_VERSION                     1000
#define IDC_FIELD1_LABEL                1001
#define IDS_LAYER_MERGE_CONFIRM         1001
#define IDC_OBJECTS                     1001
#define IDC_UNIT_ENGLISH                1002
#define IDC_FIELD2_LABEL                1002
#define IDC_SELECTABLE                  1002
#define IDS_MAY_NOT_MODIFY              1002
#define IDC_UNIT_METRIC                 1003
#define IDC_UNITS_DISPLAY               1004
#define IDC_FIELD4_LABEL                1004
#define IDS_DONE                        1004
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_DEMO                        1004
#define IDC_HIDE_METRIC_UNITS           1005
#define IDC_FIELD5_LABEL                1005
#define IDS_NONE_FOUND                  1005
#define IDC_UNITS_PLACES                1006
#define IDS_FOUND                       1006
#define IDC_DEFAULT_SCALE               1007
#define CG_IDS_PROGRESS_CAPTION         1007
#define IDC_ANGLE_DECIMAL_DEGREES       1008
#define IDS_EXCEL_NOT_FOUND             1008
#define IDC_ORGANIZATION                1008
#define IDC_ANGLE_DEGREES_MIN           1009
#define IDS_FILLET_2LINES_ERR           1009
#define IDC_ANGLE_DEGREES_MIN_SEC       1010
#define IDC_SERIAL                      1010
#define IDC_FIELD1_VALUE                1011
#define IDC_ANGLE_PLACES                1011
#define IDS_CAN_NOT_EXTEND              1011
#define IDC_FIELD2_VALUE                1012
#define IDC_DIMENSION_STATUS            1012
#define IDS_CAN_NOT_MAKE_FILLET         1012
#define IDC_FIELD3_VALUE                1013
#define IDC_DIMENSION_STANDARD          1013
#define IDC_FIELD4_VALUE                1014
#define IDC_CUSTOM                      1014
#define IDC_FIELD5_VALUE                1015
#define IDC_ANGLE_PLACES_STATIC         1015
#define IDS_NO_COMMON_INTERSECTION      1015
#define IDS_TRIM_2LINES_ERR             1016
#define IDS_LINES_DO_NOT_INTERSECT      1017
#define IDS_CHAMFER_2LINES_ERR          1018
#define IDS_CHAMFER_LENGTH_ERR          1019
#define IDC_FIELD1_USE                  1021
#define IDC_FIELD2_USE                  1022
#define IDC_FIELD3_USE                  1023
#define IDC_FIELD4_USE                  1024
#define IDS_SELECTION_INCOMPATIBLE      1024
#define IDC_FIELD5_USE                  1025
#define IDS_TANGENT_NOT_EXIST           1025
#define IDC_REFERENCE                   1026
#define IDS_CLONE_AGAIN                 1026
#define IDS_RENAME                      1027
#define IDS_RENAME_PROMPT               1027
#define IDS_CANT_RESIZE                 1028
#define IDS_INCOMPATIBLE_TIFF           1029
#define IDS_CANT_MOVE                   1030
#define IDC_FIELD1_FIND                 1031
#define IDS_LOW_RESOURCES               1031
#define IDC_FIELD2_FIND                 1032
#define IDS_LOW_MEMORY                  1032
#define IDC_FIELD3_FIND                 1033
#define IDS_UNITS_NOT_CHANGED           1033
#define IDC_FIELD4_FIND                 1034
#define IDS_CANT_LOAD_LAYER             1034
#define IDC_FIELD5_FIND                 1035
#define IDS_NOT_COMPLETED               1035
#define IDS_MEMFREE                     1036
#define IDS_SCALETOOBIG                 1037
#define IDS_VERSION                     1039
#define IDS_OBJECTS                     1040
#define IDC_FIELD1_REPLACE              1041
#define IDS_COMPOSING                   1041
#define IDC_FIELD2_REPLACE              1042
#define IDS_SELECTABLE                  1042
#define IDC_FIELD3_REPLACE              1043
#define IDS_SYMBOLS                     1043
#define IDC_FIELD4_REPLACE              1044
#define IDC_FIELD5_REPLACE              1045
#define IDC_MINUTE_SYMBOL               1050
#define IDS_SERIAL_CLASH                1050
#define IDC_SECOND_SYMBOL               1051
#define IDS_STATIONERYFILTER            1051
#define IDS_MACFILTER                   1052
#define IDS_WINDRAFTFILTER              1053
#define IDS_DXFFILTER                   1054
#define IDS_DWGFILTER                   1055
#define IDS_BITMAPFILTER                1056
#define IDS_SAVEFILTERS                 1057
#define IDS_SAVEFILTERSPE               1058
#define IDS_LOADLAYERFILTERS            1059
#define IDC_SCALE                       1060
#define IDC_PARAM1_LABEL                1060
#define IDS_LOADLAYERFILTERSPE          1060
#define IDC_PARAM2_LABEL                1061
#define IDS_EXPORTREPORTFILTERS         1061
#define IDC_PARAM1_VALUE                1062
#define IDS_LOADREPORTFILTERS           1062
#define IDC_PARAM2_VALUE                1063
#define IDS_MACFILTER2                  1063
#define IDC_UNDO                        1070
#define IDC_BY_CENTER                   1075
#define IDC_BY_DATUM                    1076
#define IDC_PREVIEW                     1080
#define IDC_PATTERN                     1090
#define IDC_DIM_TYPE                    1090
#define IDC_COLOR                       1091
#define IDC_TEXT_DISPLAY                1091
#define IDC_CURRENT_STANDARD            1098
#define IDC_UNITS                       1099
#define IDC_DEGREE                      1100
#define IDS_EDIT_LINE_STYLES            1100
#define IDC_WINDOW_AT_START_UP          1101
#define IDC_MINUTE                      1101
#define IDC_SELECTED_OPTIONS            1101
#define IDC_LAYER_LIST                  1101
#define IDC_SIZE_INCHES                 1101
#define IDC_ABSOLUTE                    1101
#define IDC_ALL_LAYERS                  1101
#define IDC_SCALE_AND_LAYER_SETUP       1101
#define IDC_MANUALLY                    1101
#define IDC_INCH                        1101
#define IDC_DIRECTION                   1101
#define IDC_OBJECT_CLASS                1101
#define IDC_REDUCE_TO_FIT               1101
#define IDC_POSITION_X                  1101
#define IDC_PATTERN_SIZE8               1101
#define IDC_COPIES                      1101
#define IDS_COLORS                      1101
#define IDC_SECOND                      1102
#define IDC_SELECTED_DATUM              1102
#define IDC_CURRENT_FILL                1102
#define IDC_LAYER_NAME                  1102
#define IDC_PRORTIONAL                  1102
#define IDC_SIZE_CM                     1102
#define IDC_RELATIVE                    1102
#define IDC_FIND_USE_MOUSE              1102
#define IDC_DIM_STANDARDS               1102
#define IDC_AUTOMATIC                   1102
#define IDC_CM                          1102
#define IDC_2DIRECTION                  1102
#define IDC_OBJECT_TYPE                 1102
#define IDC_FULL_SIZE                   1102
#define IDC_POSITION_Y                  1102
#define IDC_PATTERN_SIZE16              1102
#define IDS_EDIT_COLORS                 1102
#define IDC_CLOCKWISE                   1103
#define IDC_ALIGN_TO_OBJ                1103
#define IDC_EDIT_LAYER                  1103
#define IDC_INCREMENTAL                 1103
#define IDC_PAGE_NUMBERING_1324         1103
#define IDC_TOLAYER                     1103
#define IDC_REPLACE_USE_MOUSE           1103
#define IDC_DIM_FORMATS                 1103
#define IDC_SECONDS                     1103
#define IDC_RULER                       1103
#define IDC_DIR1_COPIES                 1103
#define IDC_PEN_COLOR                   1103
#define IDC_USE1_AS_MASTER              1103
#define IDC_MEASURE_X                   1103
#define IDC_PATTERN_SIZE32              1103
#define IDS_PATTERNS                    1103
#define IDC_ABOUT_CENTER                1104
#define IDC_ALIGN_TO_POINT              1104
#define IDC_SHOW_CURSOR_POSITION        1104
#define IDC_CURRENT_PEN                 1104
#define IDC_RENAME                      1104
#define IDC_ANGLE                       1104
#define IDC_PAGE_NUMBERING_1234         1104
#define IDC_MOVE_COPY                   1104
#define IDC_REPLACE_TYPE                1104
#define IDC_DIM_ENDMARKS                1104
#define IDC_LAYER1_AS_MASTER            1104
#define IDC_POS                         1104
#define IDC_PEN_PATTERN                 1104
#define IDC_MEASURE_Y                   1104
#define IDC_DIR1_DISTANCE_ANGLE         1104
#define IDS_EDIT_PATTERNS               1104
#define IDC_ABOUT_DATUM                 1105
#define IDC_ALIGN_TO_GRID               1105
#define IDC_CROSS_CURSOR                1105
#define IDC_ADD                         1105
#define IDC_ROTATE_COPIES               1105
#define IDC_PRINT_LAST_PAGE_FIRST       1105
#define IDC_FOUND                       1105
#define IDC_DRAW_AND_PAGE_SETUP         1105
#define IDC_CLEAR                       1105
#define IDC_SAMPLE                      1105
#define IDC_DIR1_OFFSET                 1105
#define IDC_PEN_COLOR_PICKER            1105
#define IDS_FILLCOLOR                   1105
#define IDC_ABOUT_POINT                 1106
#define IDC_REFERENCE_OPTIONS           1106
#define IDC_ZOOM_LINE_WEIGHTS           1106
#define IDC_HIDDEN                      1106
#define IDC_DRAWING_SIZE_PLACE_HOLDER   1106
#define IDC_FIND                        1106
#define IDC_FILL_PATTERNS_COLORS        1106
#define IDC_DIR1_PARAM1_LABEL           1106
#define IDC_FILL                        1106
#define IDC_PEN_PATTERN_PICKER          1106
#define IDC_DRAW                        1106
#define IDC_CIRCLES                     1106
#define IDS_PARALLELCOLOR               1106
#define IDC_REFERENCE_DATUM             1107
#define IDC_HIDE_LINE_STYLE             1107
#define IDC_GRAYED                      1107
#define IDC_REPLACE                     1107
#define IDC_LINE_SETTINGS               1107
#define IDC_REVERT                      1107
#define IDC_DIR1_PARAM2_LABEL           1107
#define IDC_FILL_COLOR                  1107
#define IDC_PRINT_REGISTRATION_MARKS    1107
#define IDS_PENCOLOR                    1107
#define IDC_TEXT                        1108
#define IDC_TOOL_DISPLAY                1108
#define IDC_ARRANGE                     1108
#define IDC_REPLACE_ALL                 1108
#define IDC_TEXT_SETTINGS               1108
#define IDC_OTHER                       1108
#define IDC_DIR1_PARAM1_VALUE           1108
#define IDC_FILL_PATTERN                1108
#define IDC_SHIFT                       1108
#define IDS_FILLPATTERN                 1108
#define IDC_TOOL_SAVE_LOCATION          1109
#define IDC_MERGE                       1109
#define IDC_CENTRE_X                    1109
#define IDC_SNAP_TO_OBJECT              1109
#define IDC_INVERT                      1109
#define IDC_DIR1_PARAM2_VALUE           1109
#define IDC_FILL_COLOR_PICKER           1109
#define IDC_NOTE                        1109
#define IDS_PARALLELPATTERN             1109
#define IDC_DELETE                      1110
#define IDC_CENTRE_Y                    1110
#define IDC_FIELD_NAMES                 1110
#define IDC_FLIP_HORIZONTAL             1110
#define IDC_DIR2_COPIES                 1110
#define IDC_FILL_PATTERN_PICKER         1110
#define IDS_PENPATTERN                  1110
#define IDC_USE_MOUSE_CLICK             1111
#define IDC_OPEN_AT_CENTER              1111
#define IDC_FLIP_VERTICAL               1111
#define IDC_LINE_WEIGHT                 1111
#define IDC_DIR2_DISTANCE_ANGLE         1111
#define IDS_PATTERNCOLOR                1111
#define IDC_HIDE_PAGE_BREAKS            1112
#define IDC_TOOL_PEN                    1112
#define IDC_DIR2_OFFSET                 1112
#define IDC_LINE_WEIGHT_PICKER          1112
#define IDC_HIDE_GRID_LINES             1113
#define IDC_TOOL_THUMB                  1113
#define IDC_DIR2_PARAM1_LABEL           1113
#define IDC_LINE_STYLE                  1113
#define IDC_SHOW_RULERS                 1114
#define IDC_DIR2_PARAM2_LABEL           1114
#define IDC_LINE_STYLE_PICKER           1114
#define IDC_TOOL_BUCKET                 1114
#define IDC_APP_DEFAULTS                1115
#define IDC_TOOL_HAND                   1115
#define IDC_DIR2_PARAM1_VALUE           1115
#define IDC_BW                          1116
#define IDC_DIR2_PARAM2_VALUE           1116
#define IDC_EDIT                        1117
#define IDS_DELETEALLVIEWS              1120
#define IDC_LIST                        1121
#define IDS_DELETEVIEW                  1121
#define IDS_MOREVIEWS                   1122
#define IDS_PRINTREPORT                 1123
#define IDS_UPDATELINK                  1124
#define IDS_BREAKLINK                   1125
#define IDC_UNITS_PLACES_STATIC         1126
#define IDS_NOGRIDSNAP                  1126
#define IDC_FEEDBACK                    1127
#define IDS_SETGRID                     1127
#define IDC_UNSCALED                    1128
#define IDS_NOANGLESNAP                 1128
#define IDC_DATUM                       1129
#define IDS_SETANGLESNAP                1129
#define IDC_CENTER                      1130
#define IDS_METRIC_DISPLAY_FIRST        1130
#define IDC_UNITS_SCALE                 1131
#define IDC_FIELD2                      1132
#define IDC_FIELD3                      1133
#define IDS_METRIC_DISPLAY_LAST         1133
#define IDC_FIELD4                      1134
#define IDS_ENGLISH_DISPLAY_FIRST       1134
#define IDC_FIELD5                      1135
#define IDC_SYMBOL                      1136
#define IDC_ABS                         1137
#define IDC_REL                         1138
#define IDS_ENGLISH_DISPLAY_LAST        1138
#define IDC_DESCRIPTION                 1139
#define IDS_REVERT                      1139
#define IDC_LABEL1                      1140
#define IDS_LAST_SAVED                  1140
#define IDC_LABEL2                      1141
#define IDS_FILE_NOT_FOUND              1141
#define IDC_LABEL3                      1142
#define IDS_DEMO_VERSION                1142
#define IDC_LABEL4                      1143
#define IDS_DEMO                        1143
#define IDC_LABEL5                      1144
#define IDS_PRINT                       1144
#define IDC_LABEL6                      1145
#define IDS_CENTERDATUM                 1145
#define IDS_EDITDATUM                   1146
#define IDS_SINGLE                      1147
#define IDS_CHAINED                     1148
#define IDS_BASELINE                    1149
#define IDS_FORMAT                      1150
#define IDS_REPORTNAME                  1151
#define IDS_LAYERNAME                   1152
#define IDS_OBJINFO                     1153
#define IDS_PRINTELLPS                  1154
#define IDC_VIEW_LIST                   1155
#define IDS_PRINTSETUP                  1155
#define IDC_REPORT_LIST                 1156
#define IDS_UPDATE                      1156
#define IDC_COPY_TYPE                   1157
#define IDS_SAVEVIEWSHORTCUT            1157
#define IDC_RADIO2                      1158
#define IDC_DWG_METRE                   1158
#define IDS_MERGEDLAYERNAME             1158
#define IDC_RADIO3                      1159
#define IDS_RENAME_LABEL                1159
#define IDC_GOTO_WEB_PAGE               1160
#define IDS_LAYER                       1160
#define IDC_EDIT_TEXT                   1161
#define IDC_EDIT_PROMPT                 1161
#define IDS_REPORT                      1161
#define IDC_RESIZE_OPT                  1162
#define IDS_LAYERS                      1162
#define IDC_STATIC_POSITION             1163
#define IDS_REPORTS                     1163
#define IDC_STATIC_X                    1164
#define IDS_NEWSYMBOLNAME               1164
#define IDC_STATIC_Y                    1165
#define IDS_WRITINGDWG                  1165
#define IDC_FIND_STATIC                 1166
#define IDC_EDIT_PLACEHOLDER            1166
#define IDS_READINGDWG                  1166
#define IDC_REPLACE1_STATIC             1167
#define IDC_REPLACE2_STATIC             1168
#define IDC_RESIZE_MORE                 1168
#define IDC_RESIZE_LESS                 1169
#define IDC_PLACE                       1170
#define IDC_APPLY                       1173
#define IDC_APPLY_REVERSE               1174
#define IDC_LINJKED                     1175
#define IDC_LINKED                      1175
#define IDC_X                           1176
#define IDC_Y                           1177
#define IDC_ANGLE_USER_DEFINED          1178
#define IDC_USER_DEFINED_VALUE          1179
#define IDC_USER_DEFINED_STATIC         1180
#define IDC_CONTRACT_EXPAND             1181
#define IDC_USER_DEFINED_NUMERATOR      1181
#define IDC_LINKED_FEEDBACK             1182
#define IDC_USER_DEFINED_DENOMINATOR    1182
#define IDC_PARALLEL_FILL               1183
#define IDC_LINKED_DIMENSIONS           1185
#define IDC_REMOVE_LINKS                1186
#define IDC_EDIT1                       1187
#define IDC_ED_DWG_UNITS                1187
#define IDC_USER                        1187
#define IDC_EDIT_TRANSPARENCY_FILL      1187
#define IDC_SEARCH                      1187
#define IDC_RADIO1                      1188
#define IDC_DWG_FEET                    1188
#define IDC_STATIC_PENSTYLE             1189
#define IDC_EDIT2                       1189
#define IDC_EDIT_TRANSPARENCY_PFILL     1189
#define IDC_EDIT3                       1190
#define IDC_EDIT_TRANSPARENCY_PEN       1190
#define IDC_DONTSHOW                    1191
#define IDC_PASSWORD                    1192
#define IDC_GRADIENT_TYPE               1193
#define IDC_EDIT_PREVIEW                1194
#define IDC_EDIT_GRADIENT               1195
#define IDC_APPLY_TO_SELECTED           1196
#define IDC_EDIT_ROTATION               1197
#define IDC_CHECK_PREVIEW               1198
#define IDC_PLACEHOLDER1                1199
#define IDC_STATIC_ROTATION             1200
#define IDC_STATIC_MOVE_CENTER          1201
#define IDC_STATIC_SEP1                 1202
#define IDC_STATIC_SEP2                 1203
#define IDC_SLIDER                      1203
#define IDC_STATIC_SEP3                 1204
#define IDC_TREE1                       1207
#define IDC_BUTTON2                     1210
#define IDC_STATIC_LESS                 1211
#define IDC_STATIC_MORE                 1212
#define IDC_LIBRARY_OPEN                1213
#define IDC_STATIC_RESIZE               1214
#define IDC_STATIC_COUNT                1215
#define ID_TOOL_ATTRIB_FILL_MENU        1217
#define ID_TOOL_ATTRIB_PFILL_MENU       1218
#define ID_TOOL_ATTRIB_PEN_MENU         1219
#define ID_TOOL_ATTRIB_FILL_ALPHA       1220
#define ID_TOOL_ATTRIB_PFILL_ALPHA      1221
#define ID_TOOL_ATTRIB_PEN_ALPHA        1222
#define ID_TOOL_ATTRIB_FILL_ICON        1223
#define ID_TOOL_ATTRIB_PFILL_ICON       1224
#define ID_TOOL_ATTRIB_PEN_ICON         1225
#define IDC_STATIC_RESIZER              1228
#define ID_OPTIONS_AUTO_SAVE            1229
#define IDC_VERTICAL                    1229
#define IDC_HORIZONTAL                  1230
#define IDC_POSITION_LABEL              1231
#define IDC_EDIT_POSITION               1232
#define IDC_STATIC_WARNING              1233
#define IDD_CHOOSE_FONT                 1543
#define IDD_PAGE_SETUP                  1546
#define IDC_AUTO_SAVE_ON                1547
#define IDC_AUTO_SAVE_OFF               1548
#define IDC_STATIC_AUTO_SAVE_LABEL      1549
#define IDC_STATIC_AUTOSAVE_MINUTES     1550
#define IDD_OPTIONS_AUTO_SAVE           1551
#define IDC_FIELD3_LABEL                1552
#define IDC_MEMFREE                     1553
#define IDS_DATUM                       1554
#define CG_IDC_PROGDLG_PROGRESS         1555
#define IDS_FIREWALL_ALERT              2000
#define IDS_FIREWALL_ASK_CHANGE         2001
#define IDD_PARALLEL_LINE               2222
#define IDD_ROTATE_OPTIONS              2224
#define IDD_EXTEND_LINE                 2226
#define IDD_FILLET_SETUP                2228
#define IDD_TRIM_SETUP                  2230
#define IDD_CHAMFER_SETUP               2231
#define IDD_SLIDE_SHOW                  2232
#define IDB_WIDTH_MENU                  3046
#define IDB_ENDMARKS                    3048
#define IDD_MIRROR_SETUP                3440
#define ID_STYLE_TEXT                   4465
#define ID_STYLE_CRITERIA               4466
#define ID_FUNC_AREA                    4467
#define ID_FUNC_COUNT                   4468
#define ID_FUNC_HEIGHT                  4469
#define ID_FUNC_LENGTH                  4470
#define ID_FUNC_PERIMETER               4471
#define ID_FUNC_WIDTH                   4472
#define ID_FUNC_XDIM                    4473
#define ID_FUNC_YDIM                    4474
#define ID_FUNC_TOTAL_NAME              4475
#define ID_FUNC_TOTAL_F2                4476
#define ID_FUNC_TOTAL_F3                4477
#define ID_FUNC_TOTAL_F4                4478
#define ID_FUNC_TOTAL_F5                4479
#define ID_UNDEFINED                    4565
#define ID_NAME                         4566
#define ID_F2                           4567
#define ID_F3                           4568
#define ID_F4                           4569
#define ID_F5                           4570
#define ID_RESULTS                      4571
#define ID_FX_NAME                      4572
#define IDB_PAT01                       5001
#define IDB_PAT02                       5002
#define IDB_PAT03                       5003
#define IDB_PAT04                       5004
#define IDB_PAT05                       5005
#define IDB_PAT06                       5006
#define IDB_PAT07                       5007
#define IDB_PAT08                       5008
#define IDB_PAT09                       5009
#define IDB_PAT10                       5010
#define IDB_PAT11                       5011
#define IDB_PAT12                       5012
#define IDB_PAT13                       5013
#define IDB_PAT14                       5014
#define IDB_PAT15                       5015
#define IDB_PAT16                       5016
#define IDB_PAT17                       5017
#define IDB_PAT18                       5018
#define IDB_PAT19                       5019
#define IDB_PAT20                       5020
#define IDB_PAT21                       5021
#define IDB_PAT22                       5022
#define IDB_PAT23                       5023
#define IDB_PAT24                       5024
#define IDB_PAT25                       5025
#define IDB_PAT26                       5026
#define IDB_PAT27                       5027
#define IDB_PAT28                       5028
#define IDB_PAT29                       5029
#define IDB_PAT30                       5030
#define IDB_PAT31                       5031
#define IDB_PAT32                       5032
#define IDB_PAT33                       5033
#define IDB_PAT34                       5034
#define IDB_PAT35                       5035
#define IDB_PAT36                       5036
#define IDB_PAT37                       5037
#define IDB_PAT38                       5038
#define IDB_PAT39                       5039
#define IDB_PAT40                       5040
#define IDB_PAT41                       5041
#define IDB_PAT42                       5042
#define IDB_PAT43                       5043
#define IDB_PAT44                       5044
#define IDB_PAT45                       5045
#define IDB_PAT46                       5046
#define IDB_PAT47                       5047
#define IDB_PAT48                       5048
#define IDB_PAT49                       5049
#define IDB_PAT50                       5050
#define IDB_PAT51                       5051
#define IDB_PAT52                       5052
#define IDB_PAT53                       5053
#define IDB_PAT54                       5054
#define IDB_PAT55                       5055
#define IDB_PAT56                       5056
#define IDB_PAT57                       5057
#define IDB_PAT58                       5058
#define IDB_PAT59                       5059
#define IDB_PAT60                       5060
#define IDB_PAT61                       5061
#define IDB_PAT62                       5062
#define IDB_PAT63                       5063
#define IDB_PAT64                       5064
#define IDB_PAT65                       5065
#define IDB_PAT66                       5066
#define IDB_PAT67                       5067
#define IDB_PAT68                       5068
#define IDB_PAT69                       5069
#define IDB_PAT70                       5070
#define IDB_PAT71                       5071
#define IDB_PL_ENDCAP2                  5072
#define IDB_PL_ENDCAP3                  5073
#define IDB_PL_ENDCAP4                  5074
#define IDB_PL_ALIGN2                   5075
#define IDB_PL_ALIGN3                   5076
#define IDB_THUMB                       5077
#define IDB_TOOL_ARC1                   5078
#define IDB_TOOL_PAN                    5078
#define IDB_TOOL_ROTATE                 5079
#define IDB_TOOL_MARQUEE                5080
#define IDB_MINI_MAXIMIZE_DOWN          5081
#define IDB_MINI_RESTORE_DOWN           5082
#define IDB_ALIGN_RIGHT                 5083
#define IDB_ALIGN_TOP                   5084
#define IDB_ALIGN_BOTTOM                5085
#define IDB_ALIGN_VCENTER               5086
#define IDB_ALIGN_HCENTER               5087
#define IDB_ALIGN_DISTH_CENTER          5088
#define IDB_ALIGN_DISTV_CENTER          5089
#define IDB_ALIGN_DISTH_DATUM           5090
#define IDB_ALIGN_DISTV_DATUM           5091
#define IDB_TOOL_LINK                   5092
#define IDB_TOOL_UNLINK                 5093
#define IDB_TOOL_MULTIUNLINK            5094
#define IDB_BUCKET_MASK                 5095
#define IDB_PFILL_MASK                  5096
#define IDB_PEN_MASK                    5097
#define IDB_PEN_MASK2                   5098
#define IDB_TOOL_STAR                   5099
#define IDB_COLOR                       5100
#define IDB_COLOR2                      5100
#define IDB_COLOR_MASK                  5101
#define IDB_ALPHA_MASK                  5102
#define IDB_ALPHA                       5103
#define IDD_RESIZE_PALETTE              5440
#define IDD_LOAD_LAYER                  5441
#define IDD_LOAD_REPORT                 5442
#define IDD_MORE_WINDOWS                5443
#define IDS_SELECT_EDGE_ARC             6101
#define IDS_SELECT_SHAPE_EDGE           6102
#define IDS_SELECT_CIRC_ARC             6104
#define IDS_SELECT_CIRC_ELLIP_ARC       6105
#define IDS_SELECT_EXTRUDE              6106
#define IDS_EXTRUDE_NOT_VALID           6107
#define IDS_SELECT_CIRCLE               6108
#define IDS_SELECT_ARC                  6109
#define IDS_SELECT_LINE                 6110
#define IDS_APPLY_ATTRIBUTES            6111
#define IDS_APPLY                       6112
#define IDS_ALREADY_TAKEN               6113
#define IDS_CONTRACT_TITLE              6114
#define IDS_CONTRACT_MSG                6115
#define IDS_EXPAND_TITLE                6116
#define IDS_EXPAND_MSG                  6117
#define IDS_UNABLE_COMPLETE_ACTION      6118
#define IDS_UNABLE_TO_ROTATE            6119
#define IDS_WARNING_GUIDE_OUTSIDE_DRAWING 6200
#define IDS_BADDWGOBJECT                6499
#define IDS_DWGQUADRATICBSPLINE         6500
#define IDS_DWGBEZIER                   6501
#define IDS_DWGDIMENSION                6502
#define IDS_DWGLEADER                   6503
#define IDS_DWGTOLERANCE                6504
#define IDS_DWGMULTILINE                6505
#define IDS_DWGIMAGE                    6506
#define IDS_DWGCIRCULARARC              6507
#define IDS_DWGMESH                     6508
#define IDS_DWGSHELL                    6509
#define IDS_DWGSHAPE                    6510
#define IDS_DWGREGION                   6511
#define IDS_DWG3DSOLID                  6514
#define IDS_DWGRAY                      6515
#define IDS_DWGCONSTRUCTIONLINE         6516
#define IDS_DWGBODY                     6517
#define IDS_DWGOLEOBJECT                6518
#define IDS_DWGHATCH                    6519
#define IDS_DWGARCALIGNEDTEXT           6521
#define IDS_DWGPOLYGONMASH              6522
#define IDS_DWGPOLYFACEMESH             6523
#define IDS_DWGFRAME                    6524
#define IDC_VERT_BAR                    8000
#define IDS_NEW_GRADIENT                8000
#define IDC_HORZ_BAR                    8001
#define IDC_POSITION                    8004
#define IDC_ZOOM                        8005
#define IDC_LAYERCTL                    8006
#define IDC_SIZE_BAR                    8007
#define IDD_PASSWORD_DLG                8008
#define IDC_EDIT_PWD                    8009
#define IDC_PASS_FILE_NAME              8010
#define IDS_LOADING_LIBRARIES           8011
#define ID_INDICATOR_PROGRESS           8012
#define IDD_ATTRIB_PALETTEx             9000
#define IDC_ORIGINAL                    9999
#define IDR_TOOL_PALETTE                20000
#define IDD_REGISTRATION                20000
#define IDR_ATTRIB_PALETTE              20001
#define IDD_BETA                        20001
#define IDR_ACC_PALETTE                 20002
#define IDD_EDIT_GRADIENT               20002
#define IDR_DIM_PALETTE                 20003
#define IDD_TRANSPARENCY_BAR            20003
#define IDR_RESIZE_PALETTE              20004
#define IDD_STAR                        20004
#define IDR_SHOWSIZE_PALETTE            20005
#define IDD_LAYER_HEADER                20005
#define IDR_ALIGN_PALETTE               20006
#define IDD_LAYER_FOOTER                20006
#define IDD_RIBBON_PROPERTIES           20007
#define IDD_ADD_GUIDE                   20008
#define IDD_ADD_GUIDE_BY_POSITION       20008
#define ID_FILLINFO                     32998
#define ID_LINEINFO                     32999
#define ID_STYLES_BASE                  33000
#define ID_EDIT_STYLES_BASE             33020
#define ID_ENDMARKS_BASE                33680
#define ID_LINE_WIDTH_BASE              33730
#define ID_GRID_BASE                    33750
#define ID_TOOL_MENU_BASE               33800
#define ID_REPORTS_BASE                 34000
#define ID_UPDATE_LINK_BASE             35000
#define ID_BREAK_LINK_BASE              36000
#define ID_VIEWS_BASE                   37000
#define ID_FILE_NEW_DRAWING             40100
#define ID_FILE_NEW_SYMBOL_LIBRARY      40101
#define ID_FILE_LOAD_LAYER              40102
#define ID_FILE_CLOSE_ALL               40103
#define ID_FILE_REVERT                  40104
#define ID_FILE_EXPORT_REPORT           40105
#define ID_FILE_PRINT_ACTIVE_LAYER      40106
#define ID_FILE_PRINT_SLIDES            40107
#define ID_FILE_SET_DEFAULTS            40108
#define ID_FILE_EXPORT_FILE             40109
#define ID_EDIT_PASTE_UNSCALED          40200
#define ID_EDIT_REPEAT_PASTE            40201
#define ID_EDIT_COPY_ATTRIB             40202
#define ID_EDIT_APPLY_ATTRIB            40203
#define ID_EDIT_APPLY_ATTRIB_MORE       40204
#define ID_EDIT_ATTRIB_OPTIONS          40205
#define ID_EDIT_DUPLUCATE               40206
#define ID_EDIT_DUP_LINEAR              40207
#define ID_EDIT_DUP_CIRCULAR            40208
#define ID_EDIT_SELECT_NONE             40209
#define ID_EDIT_SELECT_SPECIAL          40210
#define ID_EDIT_MOVE                    40211
#define ID_EDIT_RESHAPE_SMOOTH          40212
#define ID_EDIT_RESHAPE_UNSMOOTH        40213
#define ID_EDIT_DATUM                   40214
#define ID_EDIT_INSERT_ROW              40215
#define ID_EDIT_DELETE_ROW              40216
#define ID_EDIT_DUP_ON_TOP              40217
#define ID_EDIT_EXPAND                  40218
#define ID_EDIT_CONTRACT                40219
#define ID_TEXT_FONT                    40300
#define ID_TEXT_JUSTIFY_LEFT            40301
#define ID_TEXT_JUSTIFY_CENTER          40302
#define ID_TEXT_JUSTIFY_RIGHT           40303
#define ID_TEXT_LINESPACING_SINGLE      40304
#define ID_TEXT_LINESPACING_1_5SPACE    40305
#define ID_TEXT_LINESPACING_DOUBLE      40306
#define ID_TEXT_UPPERCASE               40307
#define ID_TEXT_LOWERCASE               40308
#define ID_TEXT_TITLE                   40309
#define ID_TEXT_SELECTALLTEXT           40310
#define ID_TEXT_HIDETEXT                40311
#define ID_TEXT_JUSTIFY_TOP             40312
#define ID_TEXT_JUSTIFY_MIDDLE          40313
#define ID_TEXT_JUSTIFY_BOTTOM          40314
#define ID_PREF_BORDER_LINE_INSIDE      40400
#define ID_PREF_BORDER_LINE_CENTERED    40401
#define ID_PREF_BORDER_LINE_OUTSIDE     40402
#define ID_PREF_ZOOM_LINE_WEIGHTS       40403
#define ID_PREF_HIDE_LINE_STYLE         40404
#define ID_PREF_HIDE_FILLS              40407
#define ID_PREF_CROSS_CURSOR            40408
#define ID_PREF_TOOL_OPTIONS            40409
#define ID_PREF_PENSTYLE_BLADE          40421
#define ID_PREF_PENSTYLE_ROUND          40422
#define ID_VIEW_ZOOM_OUT_4X             40450
#define ID_VIEW_ZOOM_OUT_2X             40451
#define ID_VIEW_ZOOM_IN_2X              40452
#define ID_VIEW_ZOOM_IN_4X              40453
#define ID_VIEW_ZOOM_IN_8X              40454
#define ID_VIEW_ZOOM_IN_16X             40455
#define ID_VIEW_ZOOM_IN_32X             40456
#define ID_VIEW_ZOOM_IN_64X             40457
#define ID_VIEW_RESTORE_PREV_ZOOM       40504
#define ID_VIEW_HOME_VIEW               40505
#define ID_VIEW_CURSOR_POS              40506
#define ID_VIEW_SHOW_AREA               40507
#define ID_VIEW_HIDE_AREA               40508
#define ID_VIEW_SLIDE_SHOW              40509
#define ID_VIEW_SAVE_VIEW               40510
#define ID_VIEW_DELETE_ALL_VIEWS        40511
#define ID_VIEW_SAVED_VIEW1             40512
#define ID_VIEW_SAVED_VIEW2             40513
#define ID_VIEW_SAVED_VIEW3             40514
#define ID_VIEW_SAVED_VIEW4             40515
#define ID_VIEW_SAVED_VIEW5             40516
#define ID_VIEW_MORE_VIEWS              40517
#define ID_VIEW_PALETTE_ALL             40520
#define ID_VIEW_PALETTE_TOOL            40521
#define ID_VIEW_PALETTE_ATTRIB          40522
#define ID_VIEW_PALETTE_ACC             40523
#define ID_VIEW_PALETTE_DIM             40524
#define ID_VIEW_PALETTE_SHOWSIZE        40525
#define ID_VIEW_PALETTE_RESIZE          40526
#define ID_VIEW_PALETTE_ALIGN           40527
#define ID_SAVED_VIEW1                  40530
#define ID_SAVED_VIEW2                  40531
#define ID_SAVED_VIEW3                  40532
#define ID_SAVED_VIEW4                  40533
#define ID_SAVED_VIEW5                  40534
#define ID_VIEW_HIDE_SHOW_AREA          40550
#define ID_ARRANGE_TO_FRONT             40600
#define ID_ARRANGE_TO_BACK              40601
#define ID_ARRANGE_FORWARD              40602
#define ID_ARRANGE_BACKWARD             40603
#define ID_ARRANGE_GROUP                40604
#define ID_ARRANGE_UNGROUP              40605
#define ID_ARRANGE_ROTATE               40606
#define ID_ARRANGE_ROTATE_ZERO          40607
#define ID_ARRANGE_ROTATE_OPT           40608
#define ID_ARRANGE_FLIP_HORIZ           40609
#define ID_ARRANGE_FLIP_VERT            40610
#define ID_ARRANGE_ALIGN_AGAIN          40611
#define ID_ARRANGE_ALIGN_OPT            40612
#define ID_ARRANGE_DISTRIBUTE           40613
#define ID_ARRANGE_LOCK                 40614
#define ID_ARRANGE_UNLOCK               40615
#define ID_DATA_FIELD_NAMES             40700
#define ID_DATA_OBJECT_INFO             40701
#define ID_DATA_FIND_REPLACE            40702
#define ID_DATA_REPORT_FORMATS          40703
#define ID_DATA_PRINTREPORT             40704
#define ID_DATA_UPDATELINK              40705
#define ID_DATA_BREAKLINK               40706
#define ID_LAYOUT_LAYER_SETUP           40800
#define ID_LAYOUT_SET_SCALE_UNITS       40801
#define ID_LAYOUT_SHOW_RULERS           40802
#define ID_LAYOUT_SCALE_RULERS          40803
#define ID_LAYOUT_STANDARD_RULERS       40804
#define ID_LAYOUT_SNAP_TO_OBJECT        40805
#define ID_LAYOUT_HIDE_GRID_LINES       40806
#define ID_LAYOUT_HIDE_PAGE_BREAKS      40807
#define ID_LAYOUT_DRAWING_SIZE          40808
#define ID_LAYOUT_POSITION              40809
#define ID_LAYOUT_SET_GRID_NONE         40810
#define ID_HELP_REGISTER                40820
#define ID_HELP_UPGRADE                 40821
#define ID_ANGLE_SNAP_BASE              40900
#define ID_TOOL_RADIO_FIRST             41000
#define ID_TOOL_ARROW                   41000
#define ID_TOOL_ROTATE                  41001
#define ID_TOOL_MULTI_FIRST             41002
#define ID_TOOL_MARQUEE                 41002
#define ID_TOOL_MARQUEE2                41003
#define ID_TOOL_CONSTR_LINE             41004
#define ID_TOOL_CONSTR_LINE_90          41005
#define ID_TOOL_CONSTR_LINE_45          41006
#define ID_TOOL_CONSTR_LINE_30          41007
#define ID_TOOL_CONSTR_LINE_15          41008
#define ID_TOOL_CONSTR_LINE_5           41009
#define ID_TOOL_PERP_LINE               41010
#define ID_TOOL_MIDPOINT_LINE           41011
#define ID_TOOL_ENDPOINT_LINE           41012
#define ID_TOOL_SHAPE_CENTER_LINE       41013
#define ID_TOOL_TANGENT_LINE            41014
#define ID_TOOL_CIRCLE_TANGENT_LINE     41015
#define ID_TOOL_OFFSET_LINE             41016
#define ID_TOOL_RECT                    41017
#define ID_TOOL_RECT_CENTER             41018
#define ID_TOOL_REG_POLY_SIDE_SIDE      41019
#define ID_TOOL_REG_POLY_CENTER_SIDE    41020
#define ID_TOOL_REG_POLY_VERTEX_VERTEX  41021
#define ID_TOOL_REG_POLY_CENTER_VERTEX  41022
#define ID_TOOL_RC_P                    41023
#define ID_TOOL_RC_C                    41024
#define ID_TOOL_RC_E                    41025
#define ID_TOOL_CIRCLE_D                41026
#define ID_TOOL_CIRCLE_R                41027
#define ID_TOOL_CIRCLE_3                41028
#define ID_TOOL_ELLIPSE                 41029
#define ID_TOOL_ELLIPSE_CENTER          41030
#define ID_TOOL_CIRCLE_CIRCLE           41031
#define ID_TOOL_ARC_R                   41032
#define ID_TOOL_ARC_3                   41033
#define ID_TOOL_ARC_E                   41034
#define ID_TOOL_ARC_ARC                 41035
#define ID_TOOL_POLY                    41036
#define ID_TOOL_POLY_OPEN               41037
#define ID_TOOL_CURVE                   41038
#define ID_TOOL_CURVE_CLOSED            41039
#define ID_TOOL_CURVE_BEZIER            41040
#define ID_TOOL_CURVE_CUBIC             41041
#define ID_TOOL_PARALLEL_LINE           41042
#define ID_TOOL_PARALLEL_POLY           41043
#define ID_TOOL_PARALLEL_POLY_CLOSED    41044
#define ID_TOOL_PARALLEL_LINE_EXTRUDE   41045
#define ID_TOOL_PARALLEL_POLY_EXTRUDE   41046
#define ID_TOOL_STAR_DIAMETER           41047
#define ID_TOOL_STAR_CENTER_VERTEX      41048
#define ID_TOOL_MARKER                  41049
#define ID_TOOL_REP_PASTE               41050
#define ID_TOOL_EDIT_DATUM              41051
#define ID_TOOL_MULTI_LAST              41053
#define ID_TOOL_TEXT                    41100
#define ID_TOOL_PAN                     41101
#define ID_TOOL_ATTRIB_DROP             41102
#define ID_TOOL_ZOOM                    41103
#define ID_TOOL_DIM_HORIZ               41104
#define ID_TOOL_DIM_VERT                41105
#define ID_TOOL_DIM_SLOPE               41106
#define ID_TOOL_DIM_PERP                41107
#define ID_TOOL_DIM_DIAMETER            41108
#define ID_TOOL_DIM_RADIUS              41109
#define ID_TOOL_DIM_CENTER              41110
#define ID_TOOL_DIM_ANGULAR             41111
#define ID_TOOL_HANDLE                  41112
#define ID_TOOL_RADIO_LAST              41113
#define ID_TOOL_ROTATE_90               41114
#define ID_TOOL_1_1                     41115
#define ID_TOOL_DIM_ENDMARK             41116
#define ID_TOOL_DIM_TYPE                41117
#define ID_TOOL_DIM_FORMAT              41118
#define ID_TOOL_ATTRIB_FILL             41120
#define ID_TOOL_ATTRIB_FILL_COLOR       41121
#define ID_TOOL_ATTRIB_FILL_PATTERN     41122
#define ID_TOOL_ATTRIB_FILL_TRANSPARENCY 41123
#define ID_TOOL_ATTRIB_PFILL            41124
#define ID_TOOL_ATTRIB_PFILL_COLOR      41125
#define ID_TOOL_ATTRIB_PFILL_PATTERN    41126
#define ID_TOOL_ATTRIB_PFILL_TRANSPARENCY 41127
#define ID_TOOL_ATTRIB_PEN              41128
#define ID_TOOL_ATTRIB_PEN_COLOR        41129
#define ID_TOOL_ATTRIB_PEN_PATTERN      41130
#define ID_TOOL_ATTRIB_PEN_TRANSPARENCY 41131
#define ID_TOOL_ATTRIB_LINE_WEIGTH      41132
#define ID_TOOL_ATTRIB_LINE_STYLE       41133
#define ID_TOOL_ATTRIB_END_MARK         41134
#define ID_Menu                         41146
#define ID_EDIT_REDO41147               41147
#define ID_TOOL_GLUE                    41150
#define ID_TOOL_UNGLUE                  41151
#define ID_SHOW_TOOLBAR                 41151
#define ID_TOOL_COMBINE                 41152
#define ID_TOOL_SUBTRACT                41153
#define ID_TOOL_EXTEND                  41154
#define ID_TOOL_TRIM                    41155
#define ID_TOOL_FILLET                  41156
#define ID_TOOL_CHAMFER                 41157
#define ID_TOOL_MIRROR                  41158
#define ID_TOOL_LINK                    41159
#define ID_TOOL_UNLINK                  41160
#define ID_TOOL_MULTIUNLINK             41161
#define ID_TOOL_SELECT_REF_OBJECT       41162
#define ID_LIBRARY                      41162
#define ID_TOOL_SELECT_REF_POINT        41163
#define ID_FILE_OPENLIBRARY             41163
#define ID_TOOL_DISTRIBUTE              41164
#define ID_FILE_NEWLIBRARY              41164
#define ID_TOOL_SHOWSIZE1               41165
#define ID_FILE_RENAMEITEM              41165
#define ID_TOOL_SHOWSIZE2               41166
#define ID_TOOL_SHOWSIZE3               41167
#define ID_TOOL_SHOWSIZE4               41168
#define ID_TOOL_DIM_NEXT_POINT          41169
#define ID_TOOL_PLACE                   41170
#define ID_TOOL_SELECT_LAYER            41171
#define ID_EDIT_PASTEOPTIONS            41171
#define ID_TOOL_SELECT_OBJECT           41172
#define ID_PASTEOPTIONS_PASTEUNSCALED   41172
#define ID_TOOL_SELECT_HANDLE           41173
#define ID_PASTEOPTIONS_REPEATEDPASTE   41173
#define ID_LAYOUT_SNAPTOGUIDE           41174
#define ID_LAYOUT_SNAP_TO_GUIDES        41175
#define ID_LAYOUT_SHOWGUIDELINES        41176
#define ID_LAYOUT_SHOW_GUIDE_LINES      41177
#define ID_IMAGE_ZOOMIN                 41178
#define ID_IMAGE_ZOOMOUT                41179
#define ID_Menu41180                    41180
#define ID_IMAGE_COPY                   41181
#define ID_IMAGE_PASTE                  41182
#define ID_IMAGE_PASTE41183             41183
#define ID_PASTE_PASTE                  41184
#define ID_PASTE_PASTEUNSALED           41185
#define ID_IMAGE_REPEATEDPASTE          41186
#define ID_IMAGE_DUPLICATION            41187
#define ID_DUPLICATION_DUPLICATE        41188
#define ID_DUPLICATION_DUPLICATEWITHOUTOFFSET 41189
#define ID_DUPLICATION_LINEAR           41190
#define ID_DUPLICATION_CIRCULAR         41191
#define ID_IMAGE_SELECTALL              41192
#define ID_IMAGE_SELECTSPECIAL          41193
#define ID_Menu41194                    41194
#define ID_IMAGE_EDIT                   41195
#define ID_EDIT_MOVE41196               41196
#define ID_EDIT_EXPAND41197             41197
#define ID_EDIT_EDITDATUM               41198
#define ID_EDIT_OBJECTINFO              41199
#define ID_ALIGN_LEFT                   41200
#define ID_IMAGE_ARRANGE                41200
#define ID_ALIGN_RIGHT                  41201
#define ID_IMAGE_ARRANGE41201           41201
#define ID_ALIGN_TOP                    41202
#define ID_ARRANGE_BRINGTOFONT          41202
#define ID_ALIGN_BOTTOM                 41203
#define ID_ARRANGE_SENDTOBACK           41203
#define ID_ALIGN_VCENTER                41204
#define ID_ARRANGE_MOVEFORWARD          41204
#define ID_ALIGN_HCENTER                41205
#define ID_ARRANGE_MOVEBACK             41205
#define ID_ALIGN_DISTH_CENTER           41206
#define ID_Menu41206                    41206
#define ID_ALIGN_DISTV_CENTER           41207
#define ID_ARRANGE_ROTATETOZRO          41207
#define ID_ALIGN_DISTH_DATUM            41208
#define ID_ARRANGE_ROTATEOPTIONS        41208
#define ID_ALIGN_DISTV_DATUM            41209
#define ID_ARRANGE_FLIPHORIZONTAL       41209
#define ID_DWGUNITS_GREATER_THAN_ZERO   41210
#define ID_ARRANGE_FLIIPVERTICAL        41210
#define ID_HELP_MANUAL                  41211
#define ID_IMAGE_UNGROUP                41211
#define ID_FILE_IMPORT_IMAGE            41212
#define ID_IMAGE_LOCK                   41212
#define ID_FILE_OFN                     41213
#define ID_IMAGE_UNLOCK                 41213
#define ID_PREFERENCE_DUPLICATEPATTERN  41214
#define ID                              41214
#define ID_EDIT_ZOOMIN                  41214
#define ID_NEW_GRADIENT                 41215
#define ID_EDIT_ZOOM_IN                 41215
#define ID_APPLY_TO_SELECTED            41216
#define ID_EDIT_ZOOM_OUT                41216
#define IDS_PCFILTER                    41217
#define ID_EDIT_DUPLICATE_WITHOUT_OFFSET 41217
#define IDS_INSERT_TEXT_WITH_DIFFERENT_SCALE 41218
#define ID_EDIT_EXPAND_CONTRACT         41218
#define ID_NEW_COLOR                    41219
#define ID_EDIT_SELECT_ALL_TEXT         41219
#define ID_NEW_PATTERN                  41220
#define ID_TEXT_CREATEOUTLINES          41220
#define ID_Menu41221                    41221
#define ID_GUIDES_ADDHORIZONTALGUIDE    41222
#define ID_OBJECTS_SHOWPERIMTER         41222
#define ID_GUIDES_ADDVERTICALGUIDE      41223
#define ID_VIEW_ZOOM_IN                 41223
#define ID_GUIDES_ADDGUIDEATPOSITION    41224
#define ID_EDITZOOM_IN                  41224
#define ID_VIEW_ZOOM_OUT                41225
#define ID_ARRANGE_ROTATE41226          41226
#define ID_ARRANGE_ROTATE41227          41227
#define ID_ARRANGE_ROTATE41228          41228
#define ID_FILE_NEW_FROM_TEMPLATE       41230
#define ID_TOOL_RESIZE_ABS              41250
#define ID_TOOL_RESIZE_REL              41251
#define ID_TOOL_RESIZE_TITLE            41252
#define ID_TOOL_RESIZE_LABEL1           41253
#define ID_TOOL_RESIZE_LABEL2           41254
#define ID_TOOL_RESIZE_LABEL3           41255
#define ID_TOOL_RESIZE_LABEL4           41256
#define ID_TOOL_RESIZE_LABEL5           41257
#define ID_TOOL_RESIZE_LABEL6           41258
#define ID_TOOL_RESIZE_VALUE1           41259
#define ID_TOOL_RESIZE_VALUE2           41260
#define ID_TOOL_RESIZE_VALUE3           41261
#define ID_TOOL_RESIZE_VALUE4           41262
#define ID_TOOL_RESIZE_VALUE5           41263
#define ID_TOOL_RESIZE_VALUE6           41264
#define ID_TOOL_RESIZE_POSITION_X       41265
#define ID_TOOL_RESIZE_POSITION_Y       41266
#define ID_TOOL_RESIZE_SELECTPT         41267
#define ID_TOOL_RESIZE_APPLY            41268
#define ID_PATTERNS_BASE                42000
#define ID_DUP_PATTERNS_BASE            43000
#define ID_FILL_PATTERNS_BASE           44000
#define ID_PARA_PATTERNS_BASE           45000
#define ID_PEN_PATTERNS_BASE            46000
#define ID_COLORS_BASE                  50000
#define ID_PEN_COLORS_BASE              52000
#define ID_FILL_COLORS_BASE             54000
#define ID_PARA_COLORS_BASE             56000
#define IDB_LIBRARY_ZOOM_LESS           64000
#define IDB_LIBRARY_ZOOM_MORE           64001
#define IDB_LIBRARY_OPEN                64002
#define IDB_LIBRARY_OPEN_SEL            64003
#define IDB_LAYER_ADD                   64004
#define IDB_LAYER_ADD_SEL               64005
#define IDB_LAYER_DELETE                64006
#define IDB_LAYER_DELETE_DISABLED       64007
#define IDB_LAYER_DELETE_SEL            64008
#define IDB_LAYER_MENU_SEL              64009
#define IDB_LAYER_MENU                  64010
#define IDB_LAYER_MERGE                 64011
#define IDB_LAYER_MERGE_DISABLED        64012
#define IDB_LAYER_MERGE_SEL             64013
#define ID_LAYER_ADD                    64100
#define ID_LAYER_MERGE                  64101
#define ID_LAYER_DELETE                 64102
#define ID_LAYER_RENAME                 64103
#define ID_LAYER_SHOW                   64104
#define ID_LAYER_HIDE                   64105
#define ID_LAYER_GRAY                   64106
#define ID_LAYER_MENU                   64107
#define ID_TAB_LEFT_ARROW               64200
#define ID_TAB_RIGHT_ARROW              64201
#define ID_RIBBON_LEFT_ARROW            64202
#define ID_RIBBON_RIGHT_ARROW           64203
#define ID_VIEW_HIDE_TOOLBAR            64204
#define ID_VIEW_SHOW_TOOLBAR            64205
#define IDR_XML_PAPER_CUSTOM            64206
#define IDR_XML_PRINT1                  64207
#define IDR_XML_PRINT_SETTINGS_EMPTY    64208
#define ID_Menu41176                    64209
#define IDR_XML_PAPER                   64210
#define IDS_MACFILTER3                  64211
#define IDR_XML_PRINT                   64212
#define IDR_TOOLBAR                     64300
#define IDS_CANTREDO                    64500
#define IDS_DUP_PATTERNS                64500
#define IDS_GRADIENT_RADIAL             64501
#define IDS_GRADIENT_LINEAR             64502
#define IDS_LIBRARY_DELETE_SEL_WARNING  64510
#define IDS_LIBRARYSAVEFILTERS          65000
#define IDS_LIBRARYOPENFILTERS          65001
#define ID_VIEW_PHOTO_LIBRARY           65002
#define ID_VIEW_LIBRARY                 65003
#define ID_VIEW_LAYER                   65004
#define IDS_LIBRARY_ITEM_COUNT          65005
#define IDD_LINEAR_DUP                  65006
#define IDS_DELETE_REPORT               65007
#define IDB_TOOL_DIM_DIAMETER           65008
#define IDD_REG_POLY                    65009
#define IDS_CRITERIA                    65010
#define IDS_MICROSPOT_LIBRARY           65011
#define IDS_LIBRARY                     65012
#define IDS_SELECT_MICROSPOT_LIBRARY    65013
#define IDS_CREATE_NEW_LIBRARY          65014
#define IDS_LIBRARY_ALREADY_EXISTS_WARNING 65015
#define IDS_LIBRARY_LABEL               65016
#define ID_FILE_TEMPLATE                65020
#define ID_WELCOME_SCREEN               65021
#define IDS_URL_WHATSNEW                65051
#define IDS_URL_HELPSUPPORT             65052
#define IDS_URL_COMMUNITY               65053
#define IDS_WELCOME_CANCEL              65054
#define IDS_WELCOME_OK                  65055
#define IDS_WELCOME_EDIT_NAME           65056
#define IDS_WELCOME_TO_PCDRAFT          65057
#define IDS_WELCOME_REGISTER_SERIAL     65058
#define IDS_WELCOME_REGISTER_REMARK     65059
#define IDS_WELCOME_FULL_NAME           65061
#define IDS_WELCOME_SERIAL_NO           65062
#define IDS_GETSTARTED_ALWAYS_SHOW_ON_STARTUP 65063
#define IDS_GETSTARTED_CREATE_NEW       65064
#define IDS_GETSTARTED_CHOOSE_TEMPLATE  65065
#define IDS_GETSTARTED_BROWSE_DOCUMENTS 65066
#define IDS_GETSTARTED_HELP_AND_SUPPORT 65067
#define IDS_GETSTARTED_WITH_PCDRAFT     65068
#define IDS_GETSTARTED_VERSION_70       65069
#define IDS_TEMPLATE_SEARCH_TEMPLATE    65070
#define IDS_TEMPLATE_CATEGORIES         65071
#define IDS_TEMPLATE_ALL_TEMPLATES      65072
#define IDS_TEMPLATE_SEARCH_RECENT      65073
#define IDS_WELCOME_BLANK_DOCUMENT      65074
#define ID_FILE_WELCOME_NEW             65075
#define IDS_TEMPLATE_CHOOSER            65075
#define IDS_GETSTARTED_SHORT_HELP_AND_SUPPORT 65076
#define IDS_RECENTWND_TODAY             65077
#define IDS_RECENTWND_YESTERDAY         65078
#define IDS_RECENTWND_THIS_MONTH        65079
#define IDS_RECENTWND_LAST_MONTH        65080
#define IDS_RECENTWND_EARLIER           65081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        406
#define _APS_NEXT_COMMAND_VALUE         41231
#define _APS_NEXT_CONTROL_VALUE         1234
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
